# deploy url: https://node-do-zero-7q3b.onrender.com/
# development url: http://localhost:3333/

@url = https://node-do-zero-7q3b.onrender.com
@param = videos

POST {{url}}/{{param}} 
Content-Type: application/json

{
  "title": "Video node",
  "description": "Description 1",
  "duration": 180
}

###

###

GET {{url}}/{{param}}?search=node

###

PUT {{url}}/{{param}}/0bdb7627-664f-4562-bb96-9802f697cc84
Content-Type: application/json

{
  "title": "Video de node.js",
  "description": "Description 1",
  "duration": 180
}
###

###

DELETE {{url}}/{{param}}/72c6b90c-6f53-4da4-aa80-21912a32f867
